// Mapping from CSV currency descriptions to ISO 4217 currency codes
export const currencyNameToCode: Record<string, string> = {
  "Afghanistan-Afghani": "AFN",
  "Albania-Lek": "ALL",
  "Algeria-Dinar": "DZD",
  "Angola-Kwanza": "AOA",
  "Antigua & Barbuda-East Caribbean Dollar": "XCD",
  "Argentina-Peso": "ARS",
  "Armenia-Dram": "AMD",
  "Australia-Dollar": "AUD",
  "Austria-Euro": "EUR",
  "Azerbaijan-Manat": "AZN",
  "Bahamas-Dollar": "BSD",
  "Bahrain-Dinar": "BHD",
  "Bangladesh-Taka": "BDT",
  "Barbados-Dollar": "BBD",
  "Belarus-New Ruble": "BYN",
  "Belgium-Euro": "EUR",
  "Belize-Dollar": "BZD",
  "Benin-Cfa Franc": "XOF",
  "Bermuda-Dollar": "BMD",
  "Bolivia-Boliviano": "BOB",
  "Bosnia-Marka": "BAM",
  "Botswana-Pula": "BWP",
  "Brazil-Real": "BRL",
  "Brunei-Dollar": "BND",
  "Bulgaria-Lev New": "BGN",
  "Burkina Faso-Cfa Franc": "XOF",
  "Burma-Kyat": "MMK",
  "Burundi-Franc": "BIF",
  "Cambodia-Riel": "KHR",
  "Cameroon-Cfa Franc": "XAF",
  "Canada-Dollar": "CAD",
  "Cape Verde-Escudo": "CVE",
  "Cayman Islands-Dollar": "KYD",
  "Central African Republic-Cfa Franc": "XAF",
  "Chad-Cfa Franc": "XAF",
  "Chile-Peso": "CLP",
  "China-Renminbi": "CNY",
  "Colombia-Peso": "COP",
  "Comoros-Franc": "KMF",
  "Congo-Cfa Franc": "XAF",
  "Costa Rica-Colon": "CRC",
  "Cote D'Ivoire-Cfa Franc": "XOF",
  "Croatia-Euro": "EUR",
  "Croatia-Kuna": "HRK",
  "Cross Border-Euro": "EUR",
  "Cuba-Chavito": "CUC",
  "Cuba-Peso": "CUP",
  "Curacao-Caribbean Guilder": "ANG",
  "Cyprus-Euro": "EUR",
  "Czech Republic-Koruna": "CZK",
  "Democratic Republic Of Congo-Congolese Franc": "CDF",
  "Democratic Republic Of Congo-Franc": "CDF",
  "Denmark-Krone": "DKK",
  "Djibouti-Franc": "DJF",
  "Dominican Republic-Peso": "DOP",
  "Ecuador-Dolares": "USD",
  "Egypt-Pound": "EGP",
  "El Salvador-Dollar": "USD",
  "Equatorial Guinea-Cfa Franc": "XAF",
  "Eritrea-Nakfa": "ERN",
  "Eritrea-Nakfa Salary Payment": "ERN",
  "Estonia-Euro": "EUR",
  "Eswatini-Lilangeni": "SZL",
  "Ethiopia-Birr": "ETB",
  "Euro Zone-Euro": "EUR",
  "Fiji-Dollar": "FJD",
  "Finland-Euro": "EUR",
  "France-Euro": "EUR",
  "Gabon-Cfa Franc": "XAF",
  "Gambia-Dalasi": "GMD",
  "Georgia-Lari": "GEL",
  "Germany-Euro": "EUR",
  "Ghana-Cedi": "GHS",
  "Greece-Euro": "EUR",
  "Grenada-East Caribbean Dollar": "XCD",
  "Guatemala-Quetzal": "GTQ",
  "Guinea Bissau-Cfa Franc": "XOF",
  "Guinea-Franc": "GNF",
  "Guyana-Dollar": "GYD",
  "Haiti-Gourde": "HTG",
  "Honduras-Lempira": "HNL",
  "Hong Kong-Dollar": "HKD",
  "Hungary-Forint": "HUF",
  "Iceland-Krona": "ISK",
  "India-Rupee": "INR",
  "Indonesia-Rupiah": "IDR",
  "Iran-Rial": "IRR",
  "Iraq-Dinar": "IQD",
  "Ireland-Euro": "EUR",
  "Israel-Shekel": "ILS",
  "Italy-Euro": "EUR",
  "Jamaica-Dollar": "JMD",
  "Japan-Yen": "JPY",
  "Jordan-Dinar": "JOD",
  "Kazakhstan-Tenge": "KZT",
  "Kenya-Shilling": "KES",
  "Korea-Won": "KRW",
  "Kosovo-Euro": "EUR",
  "Kuwait-Dinar": "KWD",
  "Kyrgyzstan-Som": "KGS",
  "Laos-Kip": "LAK",
  "Latvia-Euro": "EUR",
  "Lebanon-Pound": "LBP",
  "Lesotho-Maloti": "LSL",
  "Liberia-Dollar": "LRD",
  "Libya-Dinar": "LYD",
  "Lithuania-Euro": "EUR",
  "Luxembourg-Euro": "EUR",
  "Madagascar-Ariary": "MGA",
  "Malawi-Kwacha": "MWK",
  "Malaysia-Ringgit": "MYR",
  "Maldives-Rufiyaa": "MVR",
  "Mali-Cfa Franc": "XOF",
  "Malta-Euro": "EUR",
  "Marshall Islands-U.S. Dollar": "USD",
  "Mauritania-Ouguiya": "MRU",
  "Mauritius-Rupee": "MUR",
  "Mexico-Peso": "MXN",
  "Micronesia-U.S. Dollar": "USD",
  "Moldova-Leu": "MDL",
  "Mongolia-Tugrik": "MNT",
  "Montenegro-Euro": "EUR",
  "Morocco-Dirham": "MAD",
  "Mozambique-Metical": "MZN",
  "Myanmar-Kyat": "MMK",
  "Namibia-Dollar": "NAD",
  "Nepal-Rupee": "NPR",
  "Netherlands Antilles-Guilder": "ANG",
  "Netherlands-Euro": "EUR",
  "New Zealand-Dollar": "NZD",
  "Nicaragua-Cordoba": "NIO",
  "Niger-Cfa Franc": "XOF",
  "Nigeria-Naira": "NGN",
  "Norway-Krone": "NOK",
  "Oman-Rial": "OMR",
  "Pakistan-Rupee": "PKR",
  "Palau-Dollar": "USD",
  "Panama-Balboa": "PAB",
  "Panama-Dolares": "USD",
  "Papua New Guinea-Kina": "PGK",
  "Paraguay-Guarani": "PYG",
  "Peru-Sol": "PEN",
  "Philippines-Peso": "PHP",
  "Poland-Zloty": "PLN",
  "Portugal-Euro": "EUR",
  "Qatar-Riyal": "QAR",
  "Republic Of North Macedonia-Denar": "MKD",
  "Republic Of Palau-Dollar": "USD",
  "Romania-New Leu": "RON",
  "Russia-Ruble": "RUB",
  "Rwanda-Franc": "RWF",
  "Sao Tome & Principe-New Dobras": "STN",
  "Saudi Arabia-Riyal": "SAR",
  "Senegal-Cfa Franc": "XOF",
  "Serbia-Dinar": "RSD",
  "Seychelles-Rupee": "SCR",
  "Sierra Leone-Leone": "SLE",
  "Sierra Leone-Old Leone": "SLL",
  "Singapore-Dollar": "SGD",
  "Slovakia-Euro": "EUR",
  "Slovenia-Euro": "EUR",
  "Solomon Islands-Dollar": "SBD",
  "Somali-Shilling": "SOS",
  "South Africa-Rand": "ZAR",
  "South Sudan-Sudanese Pound": "SSP",
  "Spain-Euro": "EUR",
  "Sri Lanka-Rupee": "LKR",
  "St. Lucia-East Caribbean Dollar": "XCD",
  "Sudan-Pound": "SDG",
  "Suriname-Dollar": "SRD",
  "Swaziland-Lilangeni": "SZL",
  "Sweden-Krona": "SEK",
  "Switzerland-Franc": "CHF",
  "Syria-Pound": "SYP",
  "Taiwan-Dollar": "TWD",
  "Tajikistan-Somoni": "TJS",
  "Tanzania-Shilling": "TZS",
  "Thailand-Baht": "THB",
  "Timor-Leste-Dili": "USD",
  "Togo-Cfa Franc": "XOF",
  "Tonga-Pa'Anga": "TOP",
  "Trinidad & Tobago-Dollar": "TTD",
  "Tunisia-Dinar": "TND",
  "Turkey-New Lira": "TRY",
  "Turkmenistan-New Manat": "TMT",
  "Uganda-Shilling": "UGX",
  "Ukraine-Hryvnia": "UAH",
  "United Arab Emirates-Dirham": "AED",
  "United Kingdom-Pound": "GBP",
  "Uruguay-Peso": "UYU",
  "Uzbekistan-Som": "UZS",
  "Vanuatu-Vatu": "VUV",
  "Venezuela-Bolivar Soberano": "VES",
  "Venezuela-Fuerte": "VEF",
  "Vietnam-Dong": "VND",
  "Western Samoa-Tala": "WST",
  "Yemen-Rial": "YER",
  "Zambia-New Kwacha": "ZMW",
  "Zimbabwe-Gold": "ZWG",
};

// Reverse mapping: ISO code to currency name
export const codeToName: Record<string, string> = {};
for (const [name, code] of Object.entries(currencyNameToCode)) {
  // For duplicate codes (like EUR), keep the first/primary name
  if (!codeToName[code]) {
    codeToName[code] = name;
  }
}

// Add USD explicitly (not in CSV as it's the base currency)
codeToName["USD"] = "United States-Dollar";

export function getCodeFromName(name: string): string | undefined {
  return currencyNameToCode[name];
}

export function getNameFromCode(code: string): string | undefined {
  return codeToName[code];
}

export function isValidCode(code: string): boolean {
  return code === "USD" || code in codeToName;
}
